import type { HoleDef } from "./types";
import { floor, rampZ, rect } from "./dsl";

/**
 * World 1 — Sunny Meadow. A gentle ramp: each hole introduces one idea.
 * Below the course is a lake: falling off = splash (+1).
 */
export const MEADOW_HOLES: HoleDef[] = [
  {
    id: "meadow-1",
    name: "First Putt",
    par: 2,
    tee: [0, 0, 5],
    cup: [0, 0, -6],
    tip: "Drag back from the ball, release to putt.",
    pieces: [
      floor(rect(-1.6, -8, 1.6, 6.6)),
      { kind: "decor", type: "tree", at: [-3.6, -0.6, -3] },
      { kind: "decor", type: "tree", at: [3.8, -0.6, 1], scale: 1.2 },
      { kind: "decor", type: "flower", at: [2.8, -0.6, -6] },
    ],
    coins: [[1.1, 0.3, -1]],
  },
  {
    id: "meadow-2",
    name: "The Dogleg",
    par: 3,
    tee: [0, 0, 6],
    cup: [7.8, 0, -3],
    tip: "Bank it off the angled corner.",
    pieces: [
      // L-shaped fairway with a chamfered outer corner for bank shots.
      floor([
        [-1.5, 7.5],
        [1.5, 7.5],
        [1.5, -1.5],
        [9.5, -1.5],
        [9.5, -4.5],
        [0.2, -4.5],
        [-1.5, -2.8],
      ]),
      { kind: "decor", type: "tree", at: [4.5, -0.6, 3.5], scale: 1.3 },
      { kind: "decor", type: "bush", at: [3, -0.6, 1] },
      { kind: "decor", type: "pine", at: [6.5, -0.6, 2] },
    ],
    coins: [
      [-0.6, 0.3, -2.9],
      [5, 0.3, -2.2],
    ],
  },
  {
    id: "meadow-3",
    name: "Ramp It Up",
    par: 2,
    tee: [0, 0, 5.5],
    cup: [0, 1.2, -6.5],
    tip: "Give it enough juice to climb.",
    pieces: [
      floor(
        [
          [-1.5, 1],
          [1.5, 1],
          [1.5, 7],
          [-1.5, 7],
        ],
        { open: [0] },
      ),
      rampZ(-1.5, 1.5, 1, 0, -3, 1.2),
      floor(
        [
          [-2.5, -3],
          [-1.5, -3],
          [1.5, -3],
          [2.5, -3],
          [2.5, -8.5],
          [-2.5, -8.5],
        ],
        { y: 1.2, open: [1], tone: "green" },
      ),
      { kind: "decor", type: "rock", at: [-3.5, -0.6, 2] },
      { kind: "decor", type: "tree", at: [3.6, -0.6, -1] },
    ],
    coins: [[2, 1.5, -7.6]],
  },
  {
    id: "meadow-4",
    name: "Sand Trap",
    par: 3,
    tee: [0, 0, 5.5],
    cup: [0, 0, -5.4],
    tip: "Sand slows you right down. Thread the needle.",
    pieces: [
      floor(rect(-2.6, -7.6, 2.6, 7)),
      { kind: "block", at: [0, 0, 1.4], size: [1.4, 0.5, 1.2], style: "stone" },
      { kind: "sand", y: 0, pts: rect(-2.6, -4.3, -0.65, -1) },
      { kind: "sand", y: 0, pts: rect(0.65, -4.3, 2.6, -1) },
      { kind: "sand", y: 0, pts: rect(-2.6, -7.6, 2.6, -6.4) },
      { kind: "decor", type: "flower", at: [-3.6, -0.6, 4] },
      { kind: "decor", type: "tree", at: [3.8, -0.6, -4] },
    ],
    coins: [
      [-1.6, 0.3, -2.6],
      [1.6, 0.3, -2.6],
    ],
  },
  {
    id: "meadow-5",
    name: "Windmill Way",
    par: 3,
    tee: [0, 0, 6.5],
    cup: [0, 0, -5.5],
    tip: "Time it between the blades.",
    pieces: [
      floor([
        [-2, 8],
        [2, 8],
        [2, 2],
        [0.8, 2],
        [0.8, 0.7],
        [1.5, 0.7],
        [1.5, -0.7],
        [0.8, -0.7],
        [0.8, -2],
        [2.6, -2],
        [2.6, -8],
        [-2.6, -8],
        [-2.6, -2],
        [-0.8, -2],
        [-0.8, -0.7],
        [-1.5, -0.7],
        [-1.5, 0.7],
        [-0.8, 0.7],
        [-0.8, 2],
        [-2, 2],
      ]),
      { kind: "windmill", at: [0, 0], y: 0, yaw: 0, laneWidth: 1.6, speed: 1.5 },
      { kind: "decor", type: "flower", at: [-3, -0.6, 4] },
      { kind: "decor", type: "flower", at: [3.2, -0.6, 5] },
      { kind: "decor", type: "tree", at: [-4, -0.6, -4] },
    ],
    coins: [
      [-1.4, 0.3, 3.2],
      [2, 0.3, -7.3],
    ],
  },
  {
    id: "meadow-6",
    name: "Bumper Alley",
    par: 3,
    tee: [0, 0, 5.8],
    cup: [0, 0, -6.2],
    tip: "Bumpers kick back. Use them.",
    pieces: [
      floor(rect(-3.4, -8.2, 3.4, 7.2)),
      { kind: "bumper", at: [0, 1.6], y: 0, r: 0.5 },
      { kind: "bumper", at: [-1.7, -1], y: 0, r: 0.45 },
      { kind: "bumper", at: [1.7, -1], y: 0, r: 0.45 },
      { kind: "bumper", at: [0, -3.3], y: 0, r: 0.5 },
      { kind: "bumper", at: [-2.2, -4.8], y: 0, r: 0.4 },
      { kind: "bumper", at: [2.2, -4.8], y: 0, r: 0.4 },
      { kind: "decor", type: "pine", at: [-4.6, -0.6, 0] },
      { kind: "decor", type: "pine", at: [4.6, -0.6, -3] },
    ],
    coins: [
      [0, 0.3, -1.1],
      [2.7, 0.3, -7.4],
    ],
  },
  {
    id: "meadow-7",
    name: "Lily Hop",
    par: 3,
    tee: [0, 0, 7],
    cup: [0, 0, -9],
    wow: true,
    tip: "Hit the boost and fly the pond!",
    pieces: [
      floor(rect(-1.6, 2, 1.6, 8.5), { open: [0] }),
      { kind: "boost", at: [0, 3.6], y: 0, yaw: 0, length: 1.6, width: 1.2, speed: 17 },
      rampZ(-1.6, 1.6, 2, 0, -0.6, 0.75),
      floor(rect(-2.6, -11.5, 2.6, -4.8), { tone: "green" }),
      { kind: "decor", type: "flower", at: [-2.4, -1.2, -2.5] },
      { kind: "decor", type: "rock", at: [2.6, -1.2, -2] },
      { kind: "decor", type: "tree", at: [-3.8, -0.6, 5] },
    ],
    coins: [[0, 1.7, -2.8]],
  },
  {
    id: "meadow-8",
    name: "Narrow Bridge",
    par: 3,
    tee: [0, 0, 6.5],
    cup: [0, 0, -7],
    tip: "No rails. Steady hands.",
    pieces: [
      floor(
        [
          [-2, 8],
          [2, 8],
          [2, 3],
          [0.45, 3],
          [-0.45, 3],
          [-2, 3],
        ],
        { open: [3] },
      ),
      floor(
        [
          [-0.45, 3],
          [0.45, 3],
          [0.45, -4],
          [-0.45, -4],
        ],
        { rails: "none", tone: "path" },
      ),
      floor(
        [
          [-2.5, -4],
          [-0.45, -4],
          [0.45, -4],
          [2.5, -4],
          [2.5, -9.2],
          [-2.5, -9.2],
        ],
        { open: [1], tone: "green" },
      ),
      { kind: "decor", type: "rock", at: [-1.8, -1.2, 0] },
      { kind: "decor", type: "flower", at: [1.6, -1.2, -1.5] },
    ],
    coins: [[0, 0.3, -0.5]],
  },
  {
    id: "meadow-9",
    name: "Grand Loop",
    par: 3,
    tee: [0, 0, 7.5],
    cup: [1.8, 0, -7],
    wow: true,
    tip: "Full send through the loop!",
    pieces: [
      floor(
        [
          [-0.7, 0],
          [0.7, 0],
          [0.7, 4],
          [1.5, 4],
          [1.5, 8.8],
          [-1.5, 8.8],
          [-1.5, 4],
          [-0.7, 4],
        ],
        { open: [0] },
      ),
      { kind: "boost", at: [0, 2.4], y: 0, yaw: 0, length: 1.6, width: 1.1, speed: 20 },
      { kind: "loop", at: [0, 0], y: 0, yaw: 0, radius: 1.6, width: 1.4, side: 1 },
      floor(
        [
          [1.3, 0],
          [2.7, 0],
          [2.7, -3],
          [5, -3],
          [5, -9.5],
          [-1.5, -9.5],
          [-1.5, -3],
          [1.3, -3],
        ],
        { open: [0], tone: "green" },
      ),
      { kind: "decor", type: "tree", at: [-3.5, -0.6, 2] },
      { kind: "decor", type: "pine", at: [5, -0.6, 3] },
    ],
    coins: [[1.0, 2.7, 0]],
  },
];
