import type { HoleDef } from "./types";
import { floor, rect } from "./dsl";

/**
 * World 2 — Neon Night. Floating platforms over a glowing void: falling = OUT (+1).
 * Introduces teleporters, half-pipes, spinners, moving platforms, ice and one-way gates.
 */
export const NEON_HOLES: HoleDef[] = [
  {
    id: "neon-1",
    name: "Warp Zone",
    par: 2,
    tee: [0, 0, 6],
    cup: [0, 0, -10],
    tip: "Roll into the portal to warp across the void.",
    pieces: [
      floor(rect(-2, -0.5, 2, 8)),
      { kind: "teleport", a: [0, 0, 1.2], b: [0, 0, -6.2], exitYaw: 0 },
      floor(rect(-2.2, -12.2, 2.2, -5.2), { tone: "green" }),
      { kind: "decor", type: "crystal", at: [-4, 0.5, 2] },
      { kind: "decor", type: "neonRing", at: [0, -1.5, -3], scale: 1.3 },
      { kind: "decor", type: "neonPillar", at: [4, -1, -8] },
    ],
    coins: [
      [1.4, 0.3, 0.2],
      [-1.6, 0.3, -11.6],
    ],
  },
  {
    id: "neon-2",
    name: "Pinball",
    par: 3,
    tee: [0, 0, 6],
    cup: [-2.3, 0, -7.4],
    tip: "Squeeze through the gap and let the bumpers do the rest.",
    pieces: [
      floor(rect(-3.5, -9, 3.5, 7.5)),
      { kind: "block", at: [-1, 0, -1.2], size: [5, 0.5, 0.35], style: "accent" },
      { kind: "block", at: [2.9, 0, -8.4], size: [1.6, 0.5, 0.3], yaw: Math.PI / 4, style: "accent" },
      { kind: "bumper", at: [2.4, -3.8], y: 0, r: 0.45 },
      { kind: "bumper", at: [-1.4, -4.4], y: 0, r: 0.5 },
      { kind: "bumper", at: [0.6, -6.6], y: 0, r: 0.4 },
      { kind: "bumper", at: [-2.2, 2.6], y: 0, r: 0.45 },
      { kind: "bumper", at: [0.9, 3.4], y: 0, r: 0.45 },
      { kind: "decor", type: "neonPillar", at: [-5, -1, -4] },
      { kind: "decor", type: "crystal", at: [5, 0, 2] },
    ],
    coins: [
      [-2.8, 0.3, -0.4],
      [2.8, 0.3, -6.8],
    ],
  },
  {
    id: "neon-3",
    name: "Boost Lane",
    par: 3,
    tee: [-3, 0, 5.5],
    cup: [3, 0, 2.5],
    tip: "Chevrons fling you forward. Bank the corners.",
    pieces: [
      floor([
        [-4, 7],
        [-2, 7],
        [-2, -6],
        [2, -6],
        [2, 4],
        [4, 4],
        [4, -7],
        [3, -8],
        [-3, -8],
        [-4, -7],
      ]),
      { kind: "boost", at: [-3, 1], y: 0, yaw: 0, length: 1.6, width: 1.4, speed: 15 },
      { kind: "boost", at: [0, -7], y: 0, yaw: Math.PI / 2, length: 1.6, width: 1.4, speed: 13 },
      { kind: "boost", at: [3, -4.6], y: 0, yaw: Math.PI, length: 1.4, width: 1.4, speed: 9 },
      { kind: "sand", y: 0, pts: rect(2, -1.8, 4, 0.2) },
      { kind: "decor", type: "neonRing", at: [0, -1, 0], scale: 1.6 },
      { kind: "decor", type: "crystal", at: [-6, 0, -4] },
    ],
    coins: [
      [0, 0.3, -7.4],
      [-3.4, 0.3, -7.3],
    ],
  },
  {
    id: "neon-4",
    name: "Half-Pipe",
    par: 3,
    tee: [0, 0, 6.5],
    cup: [0, 0, -9.5],
    tip: "Ride the wall around the block.",
    pieces: [
      floor(
        [
          [-1.8, 4],
          [-0.6, 4],
          [0.6, 4],
          [1.8, 4],
          [1.8, 8],
          [-1.8, 8],
        ],
        { open: [1] },
      ),
      { kind: "halfpipe", from: [0, 4], to: [0, -6], y: 0, width: 1.2, radius: 1.2 },
      { kind: "block", at: [0, 0, -1], size: [0.9, 0.55, 1], style: "accent" },
      floor(
        [
          [-2.6, -6],
          [-0.6, -6],
          [0.6, -6],
          [2.6, -6],
          [2.6, -11.5],
          [-2.6, -11.5],
        ],
        { open: [1], tone: "green" },
      ),
      { kind: "decor", type: "neonPillar", at: [-4.5, -1, -1] },
      { kind: "decor", type: "neonPillar", at: [4.5, -1, -3] },
    ],
    coins: [
      [1.45, 0.75, -1],
      [-2, 0.3, -11],
    ],
  },
  {
    id: "neon-5",
    name: "Spin Cycle",
    par: 3,
    tee: [0, 0, 5.6],
    cup: [0, 0, -6.4],
    tip: "Wait for the gap… then go.",
    pieces: [
      floor([
        [-3, 7],
        [3, 7],
        [3, -7],
        [1.5, -8.5],
        [-1.5, -8.5],
        [-3, -7],
      ]),
      { kind: "spinner", at: [0, 0, -3.2], length: 2.75, speed: 1.7, arms: 2 },
      { kind: "spinner", at: [0, 0, 2], length: 1.6, speed: -1.3, arms: 3 },
      { kind: "decor", type: "crystal", at: [-5, 0, 0] },
      { kind: "decor", type: "neonRing", at: [5, -1, -4] },
    ],
    coins: [
      [-2.4, 0.3, -3.2],
      [2.4, 0.3, -3.2],
    ],
  },
  {
    id: "neon-6",
    name: "Hover Hop",
    par: 3,
    tee: [0, 0, 6],
    cup: [0, 0, -7.5],
    tip: "Ride the hover pad across. Timing is everything.",
    pieces: [
      floor(
        [
          [-2, 8],
          [-2, 2],
          [-1.1, 2],
          [1.1, 2],
          [2, 2],
          [2, 8],
        ],
        { open: [2] },
      ),
      { kind: "mover", from: [0, 0, 0.8], to: [0, 0, -2.8], size: [2.2, 0.3, 2.4], period: 7, hold: 0.2 },
      floor(
        [
          [-2.4, -4],
          [-1.1, -4],
          [1.1, -4],
          [2.4, -4],
          [2.4, -10],
          [-2.4, -10],
        ],
        { open: [1], tone: "green" },
      ),
      { kind: "decor", type: "neonRing", at: [0, -2, -1], scale: 1.8 },
      { kind: "decor", type: "crystal", at: [4, 0, -1] },
    ],
    coins: [[0, 0.45, -1]],
  },
  {
    id: "neon-7",
    name: "Ice Rink",
    par: 3,
    tee: [0, 0, 5.6],
    cup: [-1.8, 0, -8],
    tip: "Ice never stops. Use the walls.",
    pieces: [
      floor(rect(-3.5, -9.2, 3.5, 7)),
      { kind: "ice", y: 0, pts: rect(-3.5, -6.3, 3.5, 4) },
      { kind: "block", at: [-0.6, 0, -6.8], size: [5.8, 0.5, 0.35], style: "accent" },
      { kind: "block", at: [-1.5, 0, -1], size: [0.8, 0.5, 0.8], style: "crate" },
      { kind: "block", at: [1.5, 0, 1.5], size: [0.8, 0.5, 0.8], style: "crate" },
      { kind: "decor", type: "crystal", at: [-5.5, 0, 3] },
      { kind: "decor", type: "neonPillar", at: [5.5, -1, -2] },
    ],
    coins: [
      [-3, 0.3, -5.6],
      [3, 0.3, -8.5],
    ],
  },
  {
    id: "neon-8",
    name: "Gatekeeper",
    par: 4,
    tee: [0, 0, 5.5],
    cup: [0, 0, -6],
    tip: "Gates only open one way. Sneak in the back door.",
    pieces: [
      floor(rect(-4, -10.6, 4, 7)),
      { kind: "block", at: [-1.25, 0, -6], size: [0.3, 0.7, 4.6], style: "accent" },
      { kind: "block", at: [1.25, 0, -6], size: [0.3, 0.7, 4.6], style: "accent" },
      { kind: "gate", at: [0, -3.7], y: 0, yaw: Math.PI, width: 2.2 },
      { kind: "gate", at: [0, -8.3], y: 0, yaw: Math.PI, width: 2.2 },
      { kind: "bumper", at: [-2.7, -1.5], y: 0, r: 0.4 },
      { kind: "bumper", at: [2.7, -1.5], y: 0, r: 0.4 },
      { kind: "decor", type: "neonPillar", at: [-6, -1, -6] },
      { kind: "decor", type: "neonPillar", at: [6, -1, -6] },
    ],
    coins: [
      [0, 0.3, -9.7],
      [-3.2, 0.3, -6],
    ],
  },
  {
    id: "neon-9",
    name: "Neon Odyssey",
    par: 4,
    tee: [0, 0, 7.5],
    cup: [2, 2, -11.5],
    wow: true,
    tip: "Boost, loop, launch. Stick the landing.",
    pieces: [
      floor(
        [
          [-0.7, 0],
          [0.7, 0],
          [0.7, 4],
          [1.5, 4],
          [1.5, 8.8],
          [-1.5, 8.8],
          [-1.5, 4],
          [-0.7, 4],
        ],
        { open: [0] },
      ),
      { kind: "boost", at: [0, 2.4], y: 0, yaw: 0, length: 1.6, width: 1.1, speed: 20 },
      { kind: "loop", at: [0, 0], y: 0, yaw: 0, radius: 1.7, width: 1.4, side: 1 },
      floor(
        [
          [1.3, 0],
          [2.7, 0],
          [2.7, -5.5],
          [1.3, -5.5],
        ],
        { open: [0], tone: "path" },
      ),
      { kind: "bounce", at: [2, -4.6], y: 0, r: 0.65, power: 13 },
      floor(rect(-1, -14, 5, -6.5), { y: 2, open: [2], railHeight: 0.8, tone: "green" }),
      { kind: "bumper", at: [0.2, -9], y: 2, r: 0.45 },
      { kind: "bumper", at: [3.8, -9.6], y: 2, r: 0.45 },
      { kind: "decor", type: "neonRing", at: [-3, 1, -3], scale: 1.4 },
      { kind: "decor", type: "crystal", at: [6.5, 1, 2] },
    ],
    coins: [
      [1.0, 2.95, 0],
      [2, 3.4, -5.8],
    ],
  },
];
